index:
   path: /
   controller: App\Controller\PropertyController::index
# the "app_lucky_number" route name is not important yet

property:
    path: /property/
    controller: App\Controller\PropertyController::index

property_index:
    path: /property/index
    controller: App\Controller\PropertyController::index
